### ISSUE TITLE
fails to build with text-2.1.2

### ISSUE THREAD

**Issue by juhp** [facebook/Haxl#161]
For Stackage Nightly with ghc-9.10.2:

```
       Building test suite 'test' for haxl-2.5.1.1...                                                         12:58:25 [5216/954403]
       [ 1 of 26] Compiling BadDataSource
       [ 2 of 26] Compiling DataCacheTest
       /home/curators/work/unpack-dir/unpacked/haxl-2.5.1.1-e7cdb17a4921481798426074ce326ff6fcc03c190a05f95178587499c49f0eef/tests/D
ataCacheTest.hs:50:38: error: [GHC-87543]
           Ambiguous occurrence ‘show’.
           It could refer to
              either ‘Prelude.show’,
                     imported from ‘Prelude’ at tests/DataCacheTest.hs:25:1-28
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),
                  or ‘Data.Text.show’,
                     imported from ‘Data.Text’ at tests/DataCacheTest.hs:28:1-16.
          |
       50 | instance ShowP TestReq where showp = show
          |                                      ^^^^
```
