### ISSUE TITLE
haxl failing to compile with ghc-8.2 rc2

### ISSUE THREAD

**Issue by ersran9** [facebook/Haxl#70]
While trying to compile with ghc-8.2

```
    /tmp/stack12680/haxl-0.5.0.0/Haxl/Core/Types.hs:112:1: error:
        Could not find module ‘Data.Typeable.Internal’
        it is a hidden module in the package ‘base-4.10.0.0’
        Use -v to see a list of the files searched for.
        |
    112 | import Data.Typeable.Internal
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Replacing the import with `Data.Typeable` seemed to fix the issue.

compiler : The Glorious Glasgow Haskell Compilation System, version 8.2.0.20170507

**Comment by ersran9** [comment]
There's one more location with the same issue, in `Haxl.Core.DataCache`.

```
sreenidhi:~/Work/Haxl $ git diff
diff --git a/Haxl/Core/DataCache.hs b/Haxl/Core/DataCache.hs
index c40f092..aa2f3b9 100644
--- a/Haxl/Core/DataCache.hs
+++ b/Haxl/Core/DataCache.hs
@@ -28,7 +28,7 @@ import Data.Hashable
 import Prelude hiding (lookup)
 import Unsafe.Coerce
 import qualified Data.HashMap.Strict as HashMap
-import Data.Typeable.Internal
+import Data.Typeable
 import Data.Maybe
 #if __GLASGOW_HASKELL__ < 710
 import Control.Applicative ((<$>))
diff --git a/Haxl/Core/Types.hs b/Haxl/Core/Types.hs
index ef1bb5a..afb7279 100644
--- a/Haxl/Core/Types.hs
+++ b/Haxl/Core/Types.hs
@@ -110,7 +110,7 @@ import Data.List (intercalate, sortBy)
 import Data.Map (Map)
 import qualified Data.Map as Map
 import Data.Text (Text, unpack)
-import Data.Typeable.Internal
+import Data.Typeable
 
 import Haxl.Core.Exception
 #if __GLASGOW_HASKELL__ < 708
```

**Comment by ersran9** [comment]
Thanks!

**Comment by niteria** [comment]
Thanks for the report!

**Comment by phadej** [comment]
Any timeline when new version will be released? https://matrix.hackage.haskell.org/package/haxl <- red with GHC-8.2 still

**Comment by niteria** [comment]
http://hackage.haskell.org/package/haxl-0.5.1.0 has been released on hackage.

**Comment by phadej** [comment]
@niteria thanks!
